# DockerBuild Pipeline 
---
trigger:
- master

pool:
  vmImage: Ubuntu 20.04

stages:
  - stage: ContinousIntegration
    displayName: Continous Integration
    jobs:
      - job: BuildDockerContainerImage
        displayName: 'CI - Docker(Azure Container Registry)'

        steps:
          - checkout: self
            displayName: "Task - Checkout $(Build.SourceBranch)"
            persistCredentials: true

          - task: Docker@2 
            displayName: "Task - Docker Login Azure Container Registry"
            inputs:
              containerRegistry: 'servcon-acrywdevopscore'
              command: 'login'
          
          - task: Docker@2
            displayName: "Task - Build $(Build.SourceBranchName) Image"
            inputs:
              containerRegistry: 'servcon-acrywdevopscore'
              repository: '$(Build.Repository.Name)'
              command: 'build'
              Dockerfile: '$(Build.SourcesDirectory)/dockerfile'
              buildContext: '$(Build.SourcesDirectory)'
              tags: |
                $(Build.SourceBranchName)
                latest

          - task: Docker@2
            displayName: "Task - Push $(Build.SourceBranchName) Image"
            inputs:
              containerRegistry: 'servcon-acrywdevopscore'
              repository: '$(Build.Repository.Name)'
              command: 'push'
              Dockerfile: '$(Build.SourcesDirectory)/dockerfile'
              buildContext: '$(Build.SourcesDirectory)'
              tags: |
                $(Build.SourceBranchName)
                latest
