version: '3.8'

services:
  notification:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uptime-kuma
    volumes:
      #- ./data:/app/data
      - ./server:/app/server
      - ./db:/app/db
    ports:
      - "3001:3001"  # <Host Port>:<Container Port>
      - "3307:3306"
